# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.srcs/sources_1/ip/clock_VGA/clock_VGA.xci
# IP: The module: 'clock_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.srcs/sources_1/ip/clock_VGA/clock_VGA.xci
# IP: The module: 'clock_VGA' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet VGA/Code VHDL/Generateur_Pattern/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/clock_VGA/clock_VGA_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_VGA'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
