# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/utilisateur/Documents/TP/TP04 - Part2/TP04 - Pilotage/Cora-Z7-10-Master.xdc

# IP: ip/FIFO_Code_Couleur/FIFO_Code_Couleur.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==FIFO_Code_Couleur || ORIG_REF_NAME==FIFO_Code_Couleur} -quiet] -quiet
