# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.srcs/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur.xci
# IP: The module: 'FIFO_Code_Couleur' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.gen/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Code_Couleur'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.gen/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Code_Couleur'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.srcs/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur.xci
# IP: The module: 'FIFO_Code_Couleur' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.gen/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Code_Couleur'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/TP04 - Part2/LedDriver_Fifo/LedDriver/LedDriver.gen/sources_1/ip/FIFO_Code_Couleur/FIFO_Code_Couleur_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FIFO_Code_Couleur'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
