# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.srcs/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1.xci
# IP: The module: 'Fifo_ligne_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.gen/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_ligne_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.gen/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_ligne_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.srcs/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1.xci
# IP: The module: 'Fifo_ligne_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.gen/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_ligne_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/VGA_FIltre_Sobel/VGA_Sobel/VGA_Sobel.gen/sources_1/ip/Fifo_ligne_1/Fifo_ligne_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_ligne_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
