# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.srcs/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1.xci
# IP: The module: 'Fifo_Ligne1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Ligne1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Ligne1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.srcs/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1.xci
# IP: The module: 'Fifo_Ligne1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Ligne1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/utilisateur/Documents/TP/Projet_VGA/Generateur_Pattern/Generateur_Pattern.gen/sources_1/ip/Fifo_Ligne1/Fifo_Ligne1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Fifo_Ligne1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
