# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/utilisateur/Documents/TP/TP05/Cora-Z7-10-Master.xdc

# IP: ip/PLL_Clock/PLL_Clock.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PLL_Clock || ORIG_REF_NAME==PLL_Clock} -quiet] -quiet
